### ISSUE TITLE
PackageVersion is missing from the repository

### ISSUE THREAD

**Issue by ViktorHofer** [pakrym/jab#101]
I would like to use Jab in the .NET SDK as the dependency injection provider. As we have build from source requirements, we can't rely on prebuilt NuGet packages. Instead I plan to add this repo as a git submodule to our [external source build repo](https://github.com/dotnet/source-build-externals). Everything works as expected, the only thing that seems missing is the PackageVersion information.

@pakrym I assume that you manually pass in the PackageVersion before you publish the package? Can we add the PackageVersion to the Jab.csproj so that a commit corresponds to a given package version, expressed in source? When I build the repo myself I get the following package `Jab.0.5.3-beta.1.nupkg` instead of `Jab.0.8.0.nupkg`, which is the latest release on nuget.org.

**Comment by pakrym** [comment]
Will do. I think I can change the version update step I have to also change the csproj version.

**Comment by ViktorHofer** [comment]
Thanks a lot
