### ISSUE TITLE
Unexpected error during code generation - IndexOutOfRange

### ISSUE THREAD

**Issue by ErezAmihud** [pakrym/jab#109]
Hello, I have upgraded visual studio to 17.2.6 from 17.2.4 - and after the upgrade applications using jab have stopped compiling.

Most of the errors were that code was generated several times:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0579	Duplicate 'AttributeUsage' attribute	tweetz.core	C:\Users\User\work\tweetz\src\tweetz.core\Jab\Jab.ContainerGenerator\Attributes.cs	7	Active
```

But the most interasting one is the one states IndexOutOfRange:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	JAB0001	Unexpected error occurred during code generation: System.IndexOutOfRangeException: Index was outside the bounds of the array.	tweetz.core	C:\Users\User\work\tweetz\src\tweetz.core\CSC	1	
```

I am not sure what debug info I can place here that will be of any help, so please let me know :)

**Comment by ErezAmihud** [comment]
It was fixed in the preview version of visual studio

**Comment by byCrookie** [comment]
Hello. I have the same error but a different situation. If i am building locally, everything works just fine (Compiling with Rider, dotnet build, msbuild etc.). But if i build my project in my github actions using dotnet build it has following compilation errors.

`CSC : error JAB0001: Unexpected error occurred during code generation: System.IndexOutOfRangeException: Index was outside the bounds of the array. [D:\a\TypeCode\TypeCode\src\TypeCode.Wpf\TypeCode.Wpf_pa2ywpdg_wpftmp.csproj]`

`Error: D:\a\TypeCode\TypeCode\src\TypeCode.Wpf\Jab\Jab.ContainerGenerator\Attributes.cs(11,20): error CS0101: The namespace 'Jab' already contains a definition for 'ServiceProviderAttribute' [D:\a\TypeCode\TypeCode\src\TypeCode.Wpf\TypeCode.Wpf_pa2ywpdg_wpftmp.csproj]
`
These errors pop up like 50 times in a single build log. Does anybody have an idea or can tell me how to debug?

**Comment by pakrym** [comment]
I think it's a bug somewhere in roslyn/SDK. The issue seems to be in the SDK 6.0.302.

One workaround is to pin to the previous version of the SDK using global.json:
```json
{
  "sdk": {
    "version": "6.0.300",
  }
}
```

or setup exactly that version in your github action
```yaml
- uses: actions/setup-dotnet@v2
  with:
    dotnet-version: '6.0.300'
```

**Comment by byCrookie** [comment]
@pakrym Thanks a lot, I tried your solution using the exact version in my github action and it worked like a charm. Can I do something for the issue [dotnet/roslyn#62711](https://github.com/dotnet/roslyn/issues/62711), idk like an upvote? :)

And great project.

**Comment by davidwengier** [comment]
This is a WPF bug: https://github.com/dotnet/wpf/issues/6792

**Comment by debitexpress-business** [comment]
I've tried this work around in net 6.0.400 for wpf application and it works
https://github.com/Nukepayload2/MyWpfExtensionGenerator/issues/1#issue-1335806482

Hoping this will have a proper fix in the next .net version release.
