### ISSUE TITLE
Rider is unable to resolve Jab namespace

### ISSUE THREAD

**Issue by jammehcow** [pakrym/jab#114]
When creating a fresh .NET 6 console application in Rider and installing Jab 0.8.3, all references to Jab are unable to be resolved. This prevents the usage of attributes such as `[ServiceProvider]` making this library annoying to use for a Rider developer. 

I've tested this with .NET 6.0.300, 6.0.400, preview 7 of .NET 7, on both Linux & Windows but had no luck. The interesting part is that building the project with `dotnet build` or via Rider's build function, the project builds fine. It appears then to be an IDE-specific issue with discovering the Jab namespace or the likes.

On my work laptop I've been able to reproduce the issue with Rider and loading the same project with VS 2022 works fine.

The duality of IDE & build:
![image](https://user-images.githubusercontent.com/4962764/184532021-fae7abe7-5746-4b8d-b080-cfce4bb7f537.png)

**Comment by jammehcow** [comment]
I'm really keen to help resolve this but don't know where to start. If there's anything I can provide to debug this let me know.

**Comment by pakrym** [comment]
Hi! Thank you for the report.
Considering that VS and dotnet build work, this seems to be a Rider issue. Do you mind filing an issue in [rider issue tracker](https://youtrack.jetbrains.com/issues/RIDER)?

**Comment by pakrym** [comment]
[This issue](https://youtrack.jetbrains.com/issue/RIDER-80865/Source-Generators-in-Rider-20222-with-Net6-require-a-total-restart-of-Rider-to-have-the-editor-recognize-generated-symbols) looks slightly related

**Comment by jammehcow** [comment]
> I'm using Rider almost with no issues. Sometimes (rarely) I have to unload and load again the project when source generator stops working.

Interesting; reloads didn't do anything for me. I'll do some more investigation to see if it's related to the issue @pakrym mentioned above.

**Comment by jammehcow** [comment]
This might actually be a non-issue. It looks like a Rider upgrade had disabled the Roslyn analyzers setting :facepalm: 

Can confirm it's working after re-enabling it.
