### ISSUE TITLE
Auto register `IServiceScopeFactory`

### ISSUE THREAD

**Issue by skarllot** [pakrym/jab#115]
Jab could register automatically `IServiceScopeFactory` allowing to get it using `GetService` method.

Currently I need to register manually, as follows:
```csharp
[ServiceProvider]
[Transient(typeof(IServiceScopeFactory), Factory = nameof(CreateScopeFactory))]
public sealed partial class MyContainer
{
    private IServiceScopeFactory CreateScopeFactory() => this;
}
```

This allows using `CreateScope` extension method.
```csharp
var scope = ((IServiceProvider)new MyContainer()).CreateScope();
```

**Comment by pakrym** [comment]
Great idea, I'll look into it.

**Comment by pakrym** [comment]
Just checked and this should work when IServiceScopeFactory is in scope (Microsoft.Extensions.DependencyInjection is referenced). [Added a test to verify](https://github.com/pakrym/jab/pull/131).


Does your project reference Microsoft.Extensions.DependencyInjection? Can you share the generated code for you container?

**Comment by notanaverageman** [comment]
Sent PR #135 for failing test.
