### ISSUE TITLE
Jab is not working with InternalsVisibleTo

### ISSUE THREAD

**Issue by Hau-Hau** [pakrym/jab#122]
Hi and thanks for great library!

Generated attribute's file generates bunch of issues with when InternalsVisibleTo is in use.
In certain situations there is no way to build solution and current module system works well only in simple projects.
I think that it would be nice to keep Attributes.cs file in external project e.g. Jab.Abstractions.
Andrew Lock wrote article about this issue (in scope of his [StronglyTypedId](https://github.com/andrewlock/StronglyTypedId) library).
Please take a look on possible solution, here is link to article:
https://andrewlock.net/creating-a-source-generator-part-7-solving-the-source-generator-marker-attribute-problem-part1/

Here also is discussion about similar issue https://github.com/andrewlock/StronglyTypedId/issues/38

Best regards!

**Comment by pakrym** [comment]
Thanks to @skarllot's contribution, you can now reference the `Jab.Attributes` package in projects that use InternalsVisibleTo and avoid Jab-generated-type conflicts.
