### ISSUE TITLE
How do you register implementations in separate libraries?

### ISSUE THREAD

**Issue by cnayan** [pakrym/jab#125]
Is there any code sample showing registration of the implementations of interfaces in another library without exposing the implementations (internal implementations)?

**Comment by Marv51** [comment]
I have come up with a very hacky work-around for this problem, that works but is not great at all. I don't think I will use this, but I thought I might as well post it here, so maybe somebody has a better idea on how to accomplish this.

My idea was to use a factory method on a ServiceProviderModule to hide the concrete implementation.

```csharp
namespace My.Library
{

    internal class MyService : IMyService { }

    public interface IMyService { }

    [ServiceProviderModule]
    [Singleton<IMyService>(Factory = nameof(MatomoStatsFactory))]
    public partial interface IModelInitializer
    {
        // this method is needed to make Jot happy, it is not called. 
        // Instead the extension method below will be called.
        public IMyService MyServiceFactory() => throw new InvalidOperationException();
    }
}
namespace My.App
{ 
    public static class ServiceContainerExtensions
    {
        public static IMyService MyServiceFactory(this System.IServiceProvider @this)
        {
            // you can get other services like this: @this.GetRequiredService<IOtherService>()
            return new MyService();
        }
    }
}
```

**Comment by Marv51** [comment]
Aii, I just found #106, which means that the extension method is no longer needed and this should work:

```csharp
    [ServiceProviderModule]
    [Singleton<IMyService>(Factory = nameof(MyServiceFactory))]
    public partial interface IModelInitializer
    {
        public IMyService MyServiceFactory() => new MyService();
    }
```
But unfortunately I don't see any way to fetch other services inside of the static interface method.

**Comment by pakrym** [comment]
Yes, factories are the way to go here. Generated code needs something public to call. If constructor is unavailable it has to be a factory.
