### ISSUE TITLE
IServiceProvider inject

### ISSUE THREAD

**Issue by ADIX7** [pakrym/jab#126]
I'm making a console application that has commands. Commands are classes implementing an ICommand interface. All the commands are registered with the ICommand interface. I would like to create a help command (it also implements the ICommand interface) that requests registered ICommand-s. Of course this is a dependency cycle, because help command requires itself. 
Normally I would inject the service provider and resolve the commands in a "lazy" way when calling the command.

Is there any way to inject `IServiceProvider<IEnumerable<ICommand>>` into the help command?

**Comment by pakrym** [comment]
You can't inject `IServiceProvider<IEnumerable<ICommand>>` but you can inject just the `IServiceProvider provider` and resolve using `.GetService<IEnumerable<ICommand>>()`.

You might need to register the  `IEnumerable<ICommand>` [as a root type](https://github.com/pakrym/jab#root-services).
