### ISSUE TITLE
Generic attributes in .NET 7 

### ISSUE THREAD

**Issue by Unreal852** [pakrym/jab#127]
Hi, i'm using jab in a .NET 7 project  with preview lang version (upgraded from .NET 6) but i can't use generic attributes anymore.

**Comment by konrad-gora** [comment]
With .NET 7 preview lang version shouldn't be required.

**Comment by Unreal852** [comment]
Yes, but it is required by Jab, see the generated Attributes.cs class.

**Comment by konrad-gora** [comment]
Yeah, but it should be changed for c#11

**Comment by Unreal852** [comment]
Yup

**Comment by notanaverageman** [comment]
I have seen the same issue just now. Targets file checks that the framework is equal to `net6.0`. It should actually check that it is greater than or equal to.

https://github.com/pakrym/jab/blob/b74fc20f8d5a8aa55ccdd5e762513321960c9abd/src/Jab/build/Jab.targets#L3

**Comment by konrad-gora** [comment]
Also, these generic attributes are missing type constraints. Like `where TImpl: TService`. It would give us errors when writing code, not when compiling. And errors would be more clear.
