### ISSUE TITLE
Unity support (Microsoft.CodeAnalysis 3.8)

### ISSUE THREAD

**Issue by jarmo-kauko** [pakrym/jab#138]
Jab seems like a useful tool for [Unity](https://unity.com/) projects, as it provides a DI container that avoids runtime reflection and works on platforms with AOT requirements. However, [Roslyn support in Unity](https://docs.unity3d.com/2023.1/Documentation/Manual/roslyn-analyzers.html) is lacking behind and restricted to 3.8.

I was able to get Jab.Roslyn3 working in Unity by replacing
```
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.11.0" />
```
with
```
<PackageReference Include="Microsoft.CodeAnalysis" Version="3.8.0" />
<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.9.0" />
```

This causes some `[NU1608] Detected package version outside of dependency constraint` warnings, but seems to work correctly at least in basic use cases. Common 3.9.0 is required to use `RegisterForPostInitialization` API in ContainerGenerator.Roslyn3.cs.

What would be the best approach for supporting Unity projects? I can create a pull request either by modifying the Jab.Roslyn3 dependencies or by adding a new target like Jab.Unity.

**Comment by AlonTalmi** [comment]
@jarmo-kauko I tested successfully with CodeAnalysis 3.9.0 In Unity 2021.3.22.

I know [VContainer](https://github.com/hadashiA/VContainer/blob/651ab83c65e6780fc3e3aee53882dbc787885a19/VContainer.SourceGenerator/VContainer.SourceGenerator.csproj#L16C1-L16C105) uses the same version for Unity (even though VContainer's source generator is not very mature, so I'm not sure if it covers all cases)

Have you had any more insights to bumps in integrating Jab with Unity? I'm very interested in that option as well.

**Comment by AlonTalmi** [comment]
Created a upm package with extra tools to use with Jab + ready Jab dlls (from the new pull request)
https://github.com/AlonTalmi/Jab.UnityExtensions

**Comment by pakrym** [comment]
Thanks to @AlonTalmi, unity is now supported. See [installation instructions in readme](https://github.com/pakrym/jab/blob/main/README.md#Unity-installation)
