### ISSUE TITLE
Constructor from other part of a partial class is not detected and produces invalid code.

### ISSUE THREAD

**Issue by cn-ml** [pakrym/jab#140]
Hello, I'm trying to use Jab for my current project for which I previously used [AutoCtor](https://github.com/distantcam/AutoCtor) to auto-generate DI constructors for my service implementations. Now I want to use Jab to automatically create a service provider from these constructors, but i get invalid source code without any jab warning.

I produced a minimal example:

```csharp
using AutoCtor;
using Jab;

namespace JabTest;
[ServiceProvider]
[Singleton<Service1>]
[Singleton<Service2>]
public partial class Container { }

[AutoConstruct]
public partial class Service1 {
    private readonly Service2 subservice;
}

public class Service2 { }
```

The `AutoConstruct` marker generates the following code:

```csharp
namespace JabTest;
partial class Service1 {
    public Service1(Service2 subservice) => this.subservice = subservice;
}
```

However the `IServiceProvider<Service1>` implementation was generated with an invalid constructor.

```csharp
partial class Container : IServiceProvider<Service1> {
    private Service1? _Service1;
    Service1 IServiceProvider<Service1>.GetService() {
        if (_Service1 == default)
            lock (this)
                if (_Service1 == default) {
                    _Service1 = new Service1();
                }
        return _Service1;
    }
}
```

This code detected the partial class without any constructors and assumes there is no specific constructor and uses a nonexistent constructor without arguments. This code raises the compiler error: `CS7036 There is no argument given that corresponds to the required parameter 'subservice' of 'Service1.Service1(Service2)'`.

I'm not very familiar with source generation, and I've only programmed a very simple one myself once. I think the reason might be that the Jab SG executes before the AutoCtor SG does and wont detect any of it's generated code, or maybe it just ignores the fact that it is a partial class (which would likely be an easier fix).

**Comment by R2D221** [comment]
I'm not a contributor, but I think I can offer some help.

> I think the reason might be that the Jab SG executes before the AutoCtor SG does and wont detect any of it's generated code

It really doesn't matter which one it runs first. Source generators, by design, can't see each other's output. The only way I think this could work is if you add an intermediate project, so that the base project has the AutoCtor source generator, and the intermediate project has the Jab source generator.

**Comment by pakrym** [comment]
@R2D221 is right. Source generators are designed not to rely on order of execution and hence can't see each other's output.
