### ISSUE TITLE
Removing unnecessary code from output assembly

### ISSUE THREAD

**Issue by cn-ml** [pakrym/jab#150]
I just tried to migrate one of my projects from Injectio to Jab and one issue I came across is that the Marker attributes required for annotating the service provider are also contained in my output assembly when building. Is it possible to remove the attributes from the output assembly?

This is an issue to me, because it messes with the code coverage, and also because it is just not necessary to have these markers referenced in the assembly after building.

From what I see it should be possible to use conditionals or msbuild variables to hide these markers. I'm not really familiar with SG yet, but thats what I understood from Andrew Lock's [blogpost](https://andrewlock.net/series/creating-a-source-generator/).

Here is an image on how this looks on my code coverage report[^1].

![image](https://github.com/pakrym/jab/assets/18463421/86716070-d001-4eb1-bdbc-0d17ce53b077)

[^1]: Dont make fun of my coverage, I'm working on it, it's just a rapid prototype.

**Comment by pakrym** [comment]
The code has to be there because these attributes are explicitly mentioned in your code.

`Attributes.cs` is marked with `// <auto-generated/>` and should be ignored by coverage tools. Check if your code coverage tool has "Ignore generated code settings".

**Comment by cn-ml** [comment]
Not particularly sure, i assumed coverlet would take care of that by default.

Alternatively, adding an [`ExcludeFromCodeCcoverageAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.excludefromcodecoverageattribute) would likely help.

I will try to use coverage runsettings first.

**Comment by skarllot** [comment]
@pakrym What you think about adding `[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]` to the attributes and generated container?

**Comment by pakrym** [comment]
.NET uses  `System.CodeDom.Compiler.GeneratedCodeAttribute` (https://github.com/search?q=repo%3Adotnet%2Fruntime%20s_generatedCodeAttribute&type=code) would that work?

**Comment by skarllot** [comment]
> .NET uses `System.CodeDom.Compiler.GeneratedCodeAttribute` (https://github.com/search?q=repo%3Adotnet%2Fruntime%20s_generatedCodeAttribute&type=code) would that work?

Yes, I've noticed that on projects that I work the code with that attribute is not accounted in test coverage.

**Comment by pakrym** [comment]
Would you like to open a PR? 😉

**Comment by skarllot** [comment]
> Would you like to open a PR? 😉

Sure, but will take a while

**Comment by skarllot** [comment]
I think that this issue is solved now, can you confirm @cn-ml?

**Comment by pakrym** [comment]
The fix was released in 0.10.0. Thank you @skarllot !

**Comment by cn-ml** [comment]
The classes `Jab.FromNamedServicesAttribute` and `Jab.JabHelpers` are not annotated with `GeneratedCodeAttribute`. Is that on purpose?

**Comment by skarllot** [comment]
The version 0.10.1 fixes it
