### ISSUE TITLE
Abstract class with ServiceProvider shouldn't be generated, but his children should

### ISSUE THREAD

**Issue by AlonTalmi** [pakrym/jab#159]
I would have liked abstract classes to be supported in the following way:
If an abstract class has [ServiceProvider], he should be skipped from generation but instead all his closest, deep, none-abstarct children should be generated (with all of the attributes of their parents).

For example:
```
//Not generated
[ServiceProvider]
public abstract class AbstractParentSp { }

//Not generated
public abstract class AbstractChildSp : AbstractParentSp { }

//generated
public partial class ChildSp : AbstractChildSp { }

//generated
public partial class DeepChildSp : AbstractChildSp { }

//Not generated (or error?)
public class ChildOfNoneAbstractSp : ChildSp { }
```

I would love to try and open a PR for this if you like the idea

**Comment by pakrym** [comment]
Can you give me some background on when this feature might be useful?

In general, I like simple rules around when a provider gets generated, and this will make them much more complicated. I can also imagine argument to have service provider generated  for abstract classes.

**Comment by AlonTalmi** [comment]
After rethinking following your response, I think you're completely right.
What I ultimately want is the option to add registrations by inheritance.

Currently, technically there's no compile errors if you generate a service provider class to a child of another service provider, but the generated class doesn't inherit from the ancestor's IServiceProvider<T> interfaces, doesn't override the GetService method, and same is true to it's Scope class.

In my case I needed this when trying to create a Unity package using Jab, I wanted to have an abstract service provider class with extra Unity specific functionalities which I could later inherit from in projects and add my own extra registrations.

**Comment by AlonTalmi** [comment]
I'll close this issue as the original post is not really the issue, but tell me what you think about general ServiceProvider inheritance

**Comment by pakrym** [comment]
I went with the composition model for adding registrations (Modules) because it allows adding sets of registrations from multiple sources, while inheritance allows only one source and doesn't allow reordering.

Have you tried modules?

**Comment by AlonTalmi** [comment]
I have tried modules and I'm not sure what's the benefits over inheriting from an interface with attributes on it, you can still inherit from multiple interfaces and the registration order shouldn't matter.

And it also doesn't solve my use case, I want a ServiceProvider inside a package to be extendable, while not modifiable.
