### ISSUE TITLE
Why was JAB0014 introduced?

### ISSUE THREAD

**Issue by Marv51** [pakrym/jab#161]
Hi, 
could I ask about the reasoning behind "JAB0014: X parameter to construct Y will never be null when constructing using a service provider." that was recently introduced?

My class that raises the warning looks like this:
```csharp
public Foo(Bar? service, Bar2 service2){
}
```
I use Jab for my application, but construct the service manually in test cases.

The warning is absolutely correct Jab will always provide a service for the nullable parameter but for convenience in test cases this parameter is optional.
I could pretty easily rearrange the parameter to `Foo(Bar2 service2, Bar? service = null)` to make this warning go away, but I don't quite understand how that is an improvement?

There is no need to change the warning from my perspective, I will comply and rearrange my parameters. Just curious if I am doing it wrong or something else is going on.

**Comment by pakrym** [comment]
There are multiple valid ways to express the idea of a dependency being optional when designing a class in C#:
```C#
class Foo { public Foo(Bar? bar); }
class Foo { public Foo(Bar? bar = null); }
```

But only one aligns with how Jab resolution rules are set up. The diagnostic highlights that there might be a misalignment between customer expectations and Jab logic.

Think about it similar to compiler highlighting `if (a == null)` check when `a` is annotated as non-nullable. The code is fine, but the branch will never fire.

**Comment by Marv51** [comment]
Thanks for the explanation
