### ISSUE TITLE
Reference issue using generated interface

### ISSUE THREAD

**Issue by skarllot** [pakrym/jab#173]
Using a code generator for creating interfaces, Jab does not resolve namespace.

```csharp

namespace TestProject.Services;

[GenerateAutomaticInterface]
public class MyService : IMyService;
```

```csharp
namespace TestProject.Injection;

[ServiceProvider]
[Singleton<IMyService, MyService>]
public partial class MyContainer;
```

If I use complete namespace it generates a valid reference:

```csharp
namespace TestProject.Injection;

[ServiceProvider]
[Singleton<TestProject.Services.IMyService, MyService>]
public partial class MyContainer;
```

I don't know if it has a possible solution as a generator cannot access code from another generator.

**Comment by pakrym** [comment]
Unfortunately, as you've said, generators can't access each other's output so Jab can't observe the output of GenerateAutomaticInterface. This is by-design of C# compiler.
