### ISSUE TITLE
How big project can be reasonably build with jab?

### ISSUE THREAD

**Issue by kiminuo** [pakrym/jab#38]
Hi,

I have been trying to find out how large project can `jab` support so I have created this branch: https://github.com/kiminuo/jab/tree/feature/di-boom (100 000 classes)

I'm unable to even build this. :-) So just out of curiousity, do you have any idea how large project can be used with `jab`? I'm after your gut feeling not that much about some precise numbers.

Thanks!

PS: I think that at this point I have hit .NET compiler limit and not really Jab's limit.

**Comment by pakrym** [comment]
That's a great question and something that I haven't measured or optimized a lot in code.

I'm not sure we can achieve reasonable build times for 100 000 classes without some kind of a caching mechanism provided by C# compiler. At the same time, I'm confident the current source has a lot of inefficiencies that can be fixed.

**Comment by kiminuo** [comment]
I have created this branch https://github.com/kiminuo/jab/tree/feature/di-boom-no-reg which does not register classes to the container (as opposed to what https://github.com/kiminuo/jab/tree/feature/di-boom does) and .NET compiler can compile it just fine:

```
PS C:\temp\jab\src\samples\ConsoleSample> Measure-Command { dotnet build }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 6
Milliseconds      : 851
Ticks             : 68515706
TotalDays         : 7,93005856481481E-05
TotalHours        : 0,00190321405555556
TotalMinutes      : 0,114192843333333
TotalSeconds      : 6,8515706
TotalMilliseconds : 6851,5706
```

So unfortunately, it looks like this is on Jab's side. Not saying this is a common scenario to have 100,000 classes in a project but at least we have a rough estimate what is "too many".

**Comment by pakrym** [comment]
Yep, Roslyn itself is way more optimized and well designed than Jab is. I'll keep this issue open to track perf optimization of the generation.

**Comment by pakrym** [comment]
Looked into this. Actually, after some simple optimization in https://github.com/pakrym/jab/pull/70 Jab takes a reasonable 3sec to produce a generated file. What takes forever is roslyn trying to parse and compile the resulting 100MB service provider implementation.

**Comment by pakrym** [comment]
ASP.NET Core has ~1500 `(AddTransient|AddSingleton|AddScoped)` calls across all sources and tests. I'd say 2000 a good baseline for too many services :).
