### ISSUE TITLE
Is the latest Jab version 0.0.2-beta.101 really released?

### ISSUE THREAD

**Issue by kiminuo** [pakrym/jab#39]
I have tried this:

```
dotnet add package Jab --version 0.0.2-beta.101

  Determining projects to restore...
  Writing C:\Users\USERNAME\AppData\Local\Temp\tmpB3D3.tmp
info : Adding PackageReference for package 'Jab' into project 'C:\project\project.csproj'.
info : Restoring packages for C:\project\project.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/jab/index.json
error: NU1102: Unable to find package Jab with version (>= 0.0.2-beta.101)
error:   - Found 4 version(s) in nuget.org [ Nearest version: 0.0.2-beta.67 ]
error: Package 'Jab' is incompatible with 'all' frameworks in project 'C:\project\project.csproj'.
```

but it fails for me.

Thank you!

PS: Interestingly, https://www.nuget.org/packages?q=jab makes it quite hard to find the project (https://www.nuget.org/packages/Jab/0.0.2-beta.67)

**Comment by pakrym** [comment]
Hey, 

Previously I had to manually push every release to NuGet so you are right, the `101` wasn't published there.

I've added automatic NuGet publish now. 

https://www.nuget.org/packages/Jab/0.0.2-beta.105 is out

**Comment by pakrym** [comment]
>PS: Interestingly, nuget.org/packages?q=jab makes it quite hard to find the project (nuget.org/packages/Jab/0.0.2-beta.67)

Yep, NuGet search was always interesting. I guess the number of downloads skews the search result in other packages' favor.
