### ISSUE TITLE
WPF build failed

### ISSUE THREAD

**Issue by debitexpress-business** [pakrym/jab#41]
Hi,

I have been testing this project for wpf application but failed to build the app with an error "The type or namespace name 'SingletonAttribute' could not be found (are you missing a using directive or an assembly reference?)" even though roslyn analyzer found no error before building the project.

Maybe I have wrong configuration or something. This is a sample project I've created [sample project](https://github.com/pakrym/jab/files/6382579/Jab.WpfSample.zip). Hoping for someone who can enlighten me :)

Thanks a lot!

**Comment by pakrym** [comment]
Hey @debitexpress-business, it seems you are hitting https://github.com/dotnet/wpf/issues/3404


The workaround would be adding 

```xml
    <IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>
```

In your project settings.

I tested on your sample and and fixes the compilation.

**Comment by debitexpress-business** [comment]
Hi @pakrym, thank you for the work around.

Tried and it worked!

Thanks a lot!
