### ISSUE TITLE
Use Interlocked.CompareExchange instead of locking

### ISSUE THREAD

**Issue by mike-ward** [pakrym/jab#43]
The generated code uses a lock to update a stored service. Have you considered Interlocked.CompareExchange. It would avoid the context switch the lock introduces and might be faster.

```C#
if (_someService == default)
    Interlocked.CompareExchange(ref _someService, default, new MyNamespace.SomeService());
return _someService;
```

**Comment by pakrym** [comment]
The lock is used not only to synchronize the field access but also to make sure that a single instance of `MyNamespace.SomeService` independently of how many thread try to resolve it at the same time.

**Comment by mike-ward** [comment]
Ah, makes sense.
