### ISSUE TITLE
Multiple Projects Support

### ISSUE THREAD

**Issue by panoukos41** [pakrym/jab#45]
Is it possible to use it on multiple projects? Create modules in a base project using an interface and import it. or create a base class and inherit it?

I have some projects where I do this to register platform specific Implementations and Jab would be a perfect fit as it tells me when I have not implemented a service on compile time!

If you have some suggestions on how this could be achieved I am more than happy to try and implement it myself I just started learning on source generators 😄 so I am still trying to get familiar with it!

**Comment by pakrym** [comment]
Sorry for the very long delay. This should be fixed now. You can define a module in another assembly and reference it as long as all interface and implementation types are accessible.

**Comment by pakrym** [comment]
Added a sample in https://github.com/pakrym/jab/pull/51

**Comment by panoukos41** [comment]
Don't worry for the "delay" you can't be 100% above a project 😄, thanks a lot for the awesome work!!
