### ISSUE TITLE
Incompatibility with Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by Stannieman** [pakrym/jab#48]
Hi

When using Jab in a project that also has Microsoft.Extensions.DependencyInjection installed you get errors like
`ServiceProvider.Generated.cs(34,63,34,91): error CS0121: The call is ambiguous between the following methods or properties: 'Jab.ServiceProviderOfTExtensions.GetService<T>(Jab.IServiceProvider<T>)' and 'Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<T>(System.IServiceProvider)'`

You don't necessarily have to install Microsoft.Extensions.DependencyInjection directly. For example EF Core has a dependency on it so if you need EF there is no way around it.

**Comment by pakrym** [comment]
I can't repro this bug. We have a test project that references MEDI 
 and doesn't cause a similar issue https://github.com/pakrym/jab/tree/main/src/Jab.FunctionalTests.MEDI.

What versions of .NET Sdk are you using?

**Comment by Stannieman** [comment]
[DITest.zip](https://github.com/pakrym/jab/files/7486770/DITest.zip)
This reproduces it for me.
I do have the latest .NET 6 preview SDK installed on my machine so maybe there is some interference that was not there with .NET 5? Then again .NET 6 will launch in a few days anyway so it should not be a problem.

**Comment by pakrym** [comment]
Thank you for the repo. My tests and test containers are all in Jab.*** namespace that affected extension method selection and allowed them to pass. this is definitely a bug.

**Comment by Stannieman** [comment]
Woah that was fast! Thanks for the fix!
