### ISSUE TITLE
Incremental generators in .NET 6 ?

### ISSUE THREAD

**Issue by vrecluse** [pakrym/jab#54]
.NET 6 was released several days ago, and the new incremental generators should boost performance in large project.
Any ideas / plans / benchmarks?

https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md

**Comment by pakrym** [comment]
Yep, I'll definitely take a look at using incremental generators.

**Comment by vrecluse** [comment]
> Yep, I'll definitely take a look at using incremental generators.

And it would be great if Jab split it's api part and generator part.
I'm writing my own generator, which may generate some ServiceProvider for jab.
But acording to docs, generators run un-ordered.
So maybe the only way is calling jab api in my generator.
