### ISSUE TITLE
Generic service factory?

### ISSUE THREAD

**Issue by vrecluse** [pakrym/jab#55]
To create something like ILogger<T>.
Is it possible?
Or I have to register every concrete type?

**Comment by pakrym** [comment]
Yes, you can register an open-generic type like this:

``` C#
[Singleton(typeof(IService<>), typeof(ServiceImplementation<>))]
```

`ServiceImplementation` would have it generic argument populated during construction.

`IService<Program>` -> `ServiceImplementation<Program>`
