### ISSUE TITLE
Expose multiple interfaces of the same instance

### ISSUE THREAD

**Issue by Marv51** [pakrym/jab#74]
Hi! This project looks very cool from my first experiments with it. Thank you very much for all your effort. 

I have this problem: My service implements two interfaces and both of them need to be used for dependency injection and both should return the same instance.

Basically like this example (taken from [here](https://andrewlock.net/how-to-register-a-service-with-multiple-interfaces-for-in-asp-net-core-di/))
```csharp 
public interface IBar {}
public interface IFoo {}

public class Foo : IFoo, IBar {}
```
in MEDI this can be accomplished like this (taken from the same source): 
```csharp
services.AddSingleton<Foo>(); // We must explicitly register Foo
services.AddSingleton<IFoo>(x => x.GetRequiredService<Foo>()); // Forward requests to Foo
services.AddSingleton<IBar>(x => x.GetRequiredService<Foo>()); // Forward requests to Foo
```

Can this already achieved somehow in Jab? I tried to create a Factory method, but it does not seem to work correctly. I believe I am still receiving separate instances.
```csharp
[ServiceProvider]
[Scoped(typeof(Foo))]
[Scoped(typeof(IFoo), Factory = nameof(IFooFactory))]
[Scoped(typeof(IBar), Factory = nameof(IBarFactory))]
partial class ServiceContainer
{
    public IBar IBarFactory() => GetService<Foo>();
    public IFoo IFooFactory() => GetService<Foo>();
}
```

**Comment by Marv51** [comment]
Generated code, part of the Scope class:
```csharp
IFoo IServiceProvider<IFoo>.GetService(){
    if (_IFoo == default)
    lock (this)
    if (_IFoo == default){
         _IFoo = _root.IFooFactory();
    }
    return _IFoo;
}
```
I believe the "problem" here is that _root.IFooFactory will call the factory outside of the scope, so the `GetService<Foo>()` will return the unscoped Foo-Service. 

Maybe the Scope object could be passed to the factory method?

**Comment by pakrym** [comment]
This is definitely a bug.

>Maybe the Scope object could be passed to the factory method?

That's one of the options I am considering. The other is that that Scope factories should be defined in the Scope class. Like this:

```C#
        [ServiceProvider]
        [Scoped(typeof(ServiceImplementation))]
        [Scoped(typeof(IService), Factory = nameof(Scope.IServiceFactory))]
        partial class GetScopedServiceFromFactoryServiceContainer
        {
            public partial class Scope
            {
                public IService IServiceFactory(Scope scope) => scope.GetService<ServiceImplementation>();
            }
        }
```

**Comment by pakrym** [comment]
in https://www.nuget.org/packages/Jab/0.6.1 you can define a factory method on the `Scope` class like in the example above.
