### ISSUE TITLE
Two IEnumerable collide

### ISSUE THREAD

**Issue by Marv51** [pakrym/jab#75]
Hi, 
My generated container has two separate IEnumerable sets of services. It looks like Jab tries to create two (internal) properties named "_IEnumerable" both with the same name.

I'm getting this error message:
```charp
ServiceContainer.Generated.cs(115,98,115,110): error CS0102: The type 'ServiceContainer' already contains a definition for '_IEnumerable'
```

I will look further into this issue tomorrow.

**Comment by pakrym** [comment]
Should be fixed in https://www.nuget.org/packages/Jab/0.6.1
