### ISSUE TITLE
Generic Services

### ISSUE THREAD

**Issue by Marv51** [pakrym/jab#78]
Hi, thank you so much for fixing those other two issues so incredibly fast @pakrym!

I'm not quite sure what is going on with this issue, I might need to investigate more. 

I use `ILogger<>` in multiple classes. 
```csharp
class MyService(ILogger<MyService> logger) { }
class MyOtherService(ILogger<MyOtherService> logger) { }

[ServiceProvider]
[Singleton(typeof(ILogger<>), typeof(Logger<>))]
[Singleton(typeof(MyService))]
[Singleton(typeof(MyOtherService))]
partial class ServiceContainer { }
```
This does not work, as it tries to insert the same `ILogger<MyService>` into the `MyOtherService` constructor.

I tried helping Jab by setting the needed services as rootServices but to no success: 

```csharp
[ServiceProvider(RootServices = new [] {
    typeof(ILogger<MyService>), 
    typeof(ILogger<MyOtherService>) })]
```

I saw that you have some functional tests the cover generic services, but this case does not seem to be covered yet. 

Thank you very much for this cool project, I really love the clean Stacktraces from using Jab.

**Comment by pakrym** [comment]
https://www.nuget.org/packages/Jab/0.6.2 should have the fix.

**Comment by Marv51** [comment]
Amazing! I'm testing it right now. Looks good so far!

**Comment by Marv51** [comment]
@pakrym I'm not very familiar with open source licensing and of course I will give you the expected credit according to the MIT-License. But would it be better to put a license header in the generated files? 
Technically, no library that you wrote is in my app, so is a MIT license notice really required? I guess people could argue that only files generated with your tool (similar to a photoeditor) where redistributed. Or is that your intention, and you only want people forking your project to keep the license?
This gets more unclear to me the more I think about it. 

Could you clarify your wishes how to interpret the license terms?

**Comment by pakrym** [comment]
>you only want people forking your project to keep the license?

That's pretty much it. Keep the license when forking the tool. No need for a notice in the resulting product.

>Technically, no library that you wrote is in my app, so is a MIT license notice really required? 

Technically there are two parts that end up in your project. The generated code itself and the [Attributes.cs](https://github.com/pakrym/jab/blob/main/src/Jab/Attributes.cs) file with supporting types.

At the same time, I don't feel the `Attribute.cs` file warrants a notice in the resulting app as it doesn't fit the "Substantial portion" definition of the MIT license.

>But would it be better to put a license header in the generated files?

The generated output of the tool does not inherit the license. Similar to how the output of GCC preprocessor is not covered under the GPL.

**Comment by Marv51** [comment]
@pakrym Thank you very much for the clarification.
