### ISSUE TITLE
Stylecop errors with Jab generated code

### ISSUE THREAD

**Issue by codito** [pakrym/jab#87]
Should `Attributes.cs` be marked with `<auto-generated/>` prefix comment or may be a file name like `.g.cs` or similar to indicate it is auto generated from the code analysis perspective? Roslyn logic to find if a file is auto generated rules are [here](https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/InternalUtilities/GeneratedCodeUtilities.cs).

I also tried explicitly using an `.editorconfig` file to mark `Attributes.cs` as auto generated as per docs [here](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files). However, it doesn't work as expected. Where is the file generated in the filesystem? Path mentioned by `dotnet build` (see repro below) doesn't exist.

```ini
[Attributes.cs]
generated_code = true
``` 

## Repro steps

```sh
> dotnet --version
6.0.101
> dotnet new console
> dotnet add package jab
> dotnet add package stylecop.analyzers
> dotnet build

# Build warnings
E:\tmp\trial\Jab\Jab.ContainerGenerator\Attributes.cs(155,24): warning SA1201: A interface should not follow a class [E:\tmp\trial\trial.csproj]
E:\tmp\trial\Jab\Jab.ContainerGenerator\Attributes.cs(24,16): warning SA1201: A constructor should not follow a property [E:\tmp\trial\trial.csproj]
E:\tmp\trial\Jab\Jab.ContainerGenerator\Attributes.cs(41,16): warning SA1201: A constructor should not follow a property [E:\tmp\trial\trial.csproj]
```

**Comment by codito** [comment]
Sure thing, created #88.

**Comment by pakrym** [comment]
The change is out in Jab.0.6.4

**Comment by pakrym** [comment]
Thank you for the fix!
