### ISSUE TITLE
Inject factory parameters

### ISSUE THREAD

**Issue by ettud** [pakrym/jab#90]
I think it would make sense to be able to use parameters for factory methods. For example:

    [ServiceProvider]
    [Singleton(typeof(IConfiguration), Factory = nameof(CreateConfiguration))]
    [Scoped(typeof(DatabaseContext), Factory = nameof(CreateDatabaseContext))]
    internal partial class WebApiServiceProvider
    {
        private IConfiguration CreateConfiguration()
        {
            //....
        }

        private DatabaseContext CreateDatabaseContext(IConfiguration configuration)
        {
            var connectionString = configuration.GetConnectionString("DefaultConnection");
            //...
        }
    }

Now, of course we can do it this way:

    internal partial class WebApiServiceProvider
    {
        private IConfiguration CreateConfiguration()
        {
            var dbContext = ((IServiceProvider<DatabaseContext>)this).GetService();
            //....
        }

        private DatabaseContext CreateDatabaseContext()
        {
            var configuration = ((IServiceProvider<IConfiguration>)this).GetService();
            //....
        }
    }

The only problem is that with this approach you can overlook some problems e. g. circular dependencies:

    internal partial class WebApiServiceProvider
    {
        private IConfiguration CreateConfiguration()
        {
            var dbContext = ((IServiceProvider<DatabaseContext>)this).GetService(); //do it just for the sake of example
            //...
        }

        private DatabaseContext CreateDatabaseContext()
        {
            var configuration2 = ((IServiceProvider<IConfiguration>)this).GetService();
            //...
        }
    }

While if the Jab could inject parameters he would also be able to check provider for the loops.

P. S. Came across this library while checking for compile-time service providers, looks really great!

**Comment by pakrym** [comment]
I think it's a really good idea. Way better approach than the one I currently recommend. I'll look into implementing it.
