### ISSUE TITLE
Support pointing a Factory to a Func

### ISSUE THREAD

**Issue by ViktorHofer** [pakrym/jab#96]
First of all, this library is pure gold. I love it!

When the service provider itself can't implement a factory, you want to pass that in via a Func<T>. Unfortunately it looks like jab currently doesn't support that:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0029	Cannot implicitly convert type 'System.Func<Microsoft.DotNet.ApiCompatibility.Logging.CompatibilityLoggerBase>' to 'Microsoft.DotNet.ApiCompatibility.Logging.CompatibilityLoggerBase'	Microsoft.DotNet.Compatibility.Console	C:\git\sdk\src\Compatibility\Microsoft.DotNet.Compatibility.Console\Jab\Jab.ContainerGenerator\CompatibilityServiceProvider.Generated.cs	35	Active
```

```c#
    [ServiceProvider]
    [Singleton(typeof(CompatibilityLoggerBase), Factory = nameof(LogFactory))]
    internal partial class CompatibilityServiceProvider
    {
        public Func<CompatibilityLoggerBase> LogFactory { get; }

        public CompatibilityServiceProvider(Func<CompatibilityLoggerBase> logFactory)
        {
            LogFactory = logFactory;
        }
    }
```

As far as I can tell, the relevant code that constructs the method call is https://github.com/pakrym/jab/blob/30e44dca171d2e4929ce3812920f3f983a140f7f/src/Jab/ServiceProviderBuilder.cs#L442-L459 and would need to be updated to treat Func<T> similar to a IMethodSymbol.

**Comment by pakrym** [comment]
The generator doesn't have any specialized logic for `Funcs` right now. Is there a reason why defining a method and calling the `Func` from it doesn't work (other than a slightly more verbose code)? 

``` C#
 [ServiceProvider]
    [Singleton(typeof(CompatibilityLoggerBase), Factory = nameof(LogFactory))]
    internal partial class CompatibilityServiceProvider
    {
        public Func<CompatibilityLoggerBase> LogFactoryFunc { get; }
        public CompatibilityLoggerBase  LogFactory() => LogFactoryFunc();

        public CompatibilityServiceProvider(Func<CompatibilityLoggerBase> logFactory)
        {
            LogFactory = logFactory;
        }
    }
```

**Comment by ViktorHofer** [comment]
Yes, this is mostly about verbosity. Thanks for adding support for this feature so quickly! Amazing.

**Comment by ViktorHofer** [comment]
Just noticed there is no new version on nuget.org yet. Can you please publish one?

**Comment by ViktorHofer** [comment]
Thanks a lot
